# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - bin/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true

LineLength:
  Max: 120

Style/CaseIndentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Exclude:
    - Capfile

Naming/MemoizedInstanceVariableName:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*
