require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - bin/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - vendor/**/*

Rails/ApplicationController:
  Exclude:
    - app/controllers/api/v1/base_controller.rb

Style/LineLength:
  Max: 120

Layout/CaseIndentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Exclude:
    - Capfile

Naming/MemoizedInstanceVariableName:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Naming/VariableNumber:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false   

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
