version: '3.6'

services:
  web:
    hostname: 'web'
    build:
      context: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/demo_web_app'
    env_file:
      - '.env.docker'
