ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: '0'

  ingressClassName: nginx
  tls:
    - hosts:
        - new-demoapp.strongqa.com
      secretName: demo-web-app-tls

  hosts:
    - host: 'new-demoapp.strongqa.com'
      paths:
        - path: /
          pathType: Prefix

releaseEnv: production

adminEmail: admin@strongqa.com
smtp:
    address: 'email-smtp.eu-central-1.amazonaws.com'
    port: 587
    defaultURLHost: 'new-demoapp.strongqa.com'
    domain: 'mail.strongqa.com'
    authentication: ':plain'
    enableStartTTLsAuto: true

rails:
  resources:
    limits:
    # cpu: "1"
    # memory: 200Mi
    requests:
      # cpu: 500m
      memory: 200Mi

secrets:
  smtp:
     user: userName
     password: password