name: Release Please

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    uses: strongsdcom/github-actions/.github/workflows/release-please.yaml@v2
    with:
      config-file: .github/release-please/config.json
      manifest-file: .github/release-please/manifest.json
